# Scan my node app for semantic vulnerabilities with GitHub Code Scanning
# Upload any vulnerabilities back into my GitHub Repo for developer review.
 
trigger:
- master
- azure-pipelines
 
pool:
 vmImage: 'ubuntu-latest'
 
steps:
# - task: NodeTool@0
#  inputs:
#    versionSpec: '10.x'
#  displayName: 'Install Node.js'
 
# - script: |
#    npm install
#    npm test
#    displayName: 'npm install and test'

 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
         
      chmod +x codeql-runner-linux
  displayName: 'Get latest CodeQL package. Install on Agent.'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: 'csharp/example1/NetCoreVulnerabilities.sln'

- task: DotNetCoreCLI@2
  displayName: "Build for NetCoreVulnerabilities"
  inputs:
    command: build
    projects: "csharp/example1/NetCoreVulnerabilities.sln"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      chmod +x codeql-runner-linux
      ./codeql-runner-linux init --repository SanjayaE/examples-vulnerabilities-for-GHAS --github-url https://github.com --github-auth $(GITHUB_PAT) –-config-file .github/codeql/codeql-config.yml 
  displayName: 'Initialize CodeQ Executable and create a CodeQL database'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       ./codeql-runner-linux init --repository SanjayaE/examples-vulnerabilities-for-GHAS --github-url https://github.com --github-auth $(GITHUB_PAT) –-config-file codeql-config.yml
#   displayName: 'Initialize CodeQ Executable and create a CodeQL database'

# - script: |
#    ./codeql-runner-linux init --repository octodemo/ghas-azure-devops-code-scanning --github-url https://github.com --github-auth $GITHUB_PAT
#  displayName: 'Initialize CodeQ Executable and create a CodeQL database'
 
# script: |
#    ./codeql-runner-linux analyze --repository SanjayaE/examples-vulnerabilities-for-GHAS --github-url https://github.com --github-auth $GITHUB_PAT --commit 92065de8b22bbfeda511d12571b66c9969ff593b --ref refs/heads/master- 